# fly.toml file generated for wohnungs-bot on 2023-05-31T23:04:09+02:00

app = "wohnungs-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  auto_rollback = true

[[services]]
